import mongoose from "mongoose";
import { AiPayloadBuilderService } from "./aiPayloadBuilder.service";
import { AiBrief } from "../models/AiBrief";
import { GoogleGenAI } from "@google/genai";

export class BriefService {
  constructor(private aiPayloadBuilderService: AiPayloadBuilderService) {}

  public async generateBrief(repositoryId: string, windowStart: Date, windowEnd: Date) {
    // 1 & 2 & 3. Build payload (which internally handles validation, redaction, and pseudonymization)
    const payload = await this.aiPayloadBuilderService.buildWeeklyBriefPayload(repositoryId, windowStart, windowEnd);

    try {
      if (!process.env.GEMINI_API_KEY) {
        throw new Error("GEMINI_API_KEY is missing. Falling back to deterministic brief.");
      }

      const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
      const prompt = `Analyze the following team workflow metrics and evidence cards. Note that 'metrics' and 'predictions' represent the current period, while 'previousMetrics' and 'previousPredictions' represent the preceding historical period.
Compare the current period with the previous period to identify trends. If there are significant changes, highlight them in the executive summary or add items with type 'trend_comparison'.
Provide an executive summary, list of limitations, and an array of items (each item having type 'risk_summary' | 'recommendation' | 'trend_comparison', title, detail, severity 'high'|'medium'|'low'|'info').
Output strictly in valid JSON matching this schema: { "summary": "string", "confidence": "high"|"medium"|"low", "limitations": ["string"], "items": [{ "type": "risk_summary"|"recommendation"|"trend_comparison", "title": "string", "detail": "string", "severity": "high"|"medium"|"low"|"info" }] }

Payload data: ${JSON.stringify(payload)}`;

      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: prompt,
        config: {
          responseMimeType: "application/json",
        },
      });

      const responseText = response.text || "{}";
      const parsed = JSON.parse(responseText);

      const brief = await AiBrief.create({
        repositoryId: new mongoose.Types.ObjectId(repositoryId),
        windowStart,
        windowEnd,
        status: "completed",
        summary: parsed.summary || "Summary generated by AI.",
        confidence: parsed.confidence || "medium",
        limitations: parsed.limitations || payload.limitations || [],
        items: parsed.items || [],
        isFallback: false,
      });

      return brief;
    } catch (error: any) {
      console.warn("AI Generation Error, triggering fallback:", error.message);
      // 5. Deterministic Fallback
      return this.generateDeterministicBrief(repositoryId, windowStart, windowEnd, payload);
    }
  }

  private async generateDeterministicBrief(repositoryId: string, windowStart: Date, windowEnd: Date, payload: any) {
    // Deterministic rules based on payload
    const metrics = payload.metrics;
    let summary = "Weekly sync completed. Data indicates standard team activity.";
    let items = [];

    if (metrics && metrics.bottlenecksIdentified > 0) {
      summary = `Weekly sync completed. ${metrics.bottlenecksIdentified} bottlenecks identified.`;
      items.push({
        type: "risk_summary",
        title: "Bottlenecks Detected",
        detail: `Deterministic rules found ${metrics.bottlenecksIdentified} workflow issues.`,
        severity: "medium",
        evidenceCardIds: [],
      });
    }

    const fallbackBrief = await AiBrief.create({
      repositoryId: new mongoose.Types.ObjectId(repositoryId),
      windowStart,
      windowEnd,
      status: "fallback",
      summary,
      confidence: "low",
      limitations: ["AI Service unavailable, using deterministic rules", ...(payload.limitations || [])],
      items,
      isFallback: true,
    });

    return fallbackBrief;
  }

  public async getBriefs(repositoryId: string) {
    return AiBrief.find({ repositoryId: new mongoose.Types.ObjectId(repositoryId) })
      .sort({ createdAt: -1 })
      .lean();
  }
}
